### Send a valid confirmation
POST {{restUrl}}/confirm
Content-Type: application/json

< data/confirmation.json

### Send a confirmation with invalid data
POST {{restUrl}}/confirm
Content-Type: application/json

< data/confirmation-invalid-data.json

### Send a confirmation with invalid json
POST {{restUrl}}/confirm
Content-Type: application/json

< data/invalid-json.json

### Send a valid order
POST {{restUrl}}/order
Content-Type: application/json

< data/order.json

### Send a random order
POST {{restUrl}}/order
Content-Type: application/json

< data/empty.json

### Send a order with invalid json
POST {{restUrl}}/order
Content-Type: application/json

< data/invalid-json.json