spring:
  profiles:
    active: dev
---
spring:
  application.name: producer
  main:
    banner-mode: off
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  jackson:
    serialization:
      fail-on-empty-beans: false
  config:
    activate:
      on-profile: dev

logging.level.org.apache.kafka.clients:
        producer.ProducerConfig: error

server:
  port: 8080

wiremock:
  reset-mappings-after-each-test: true
